[package]
name = "rssstv-dsp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
std = ["thiserror/std"]

[dependencies]
libm = "0.2"
thiserror = { version = "2.0", default-features = false }

[dev-dependencies]
rstest = "0.26"
