[package]
name = "rssstv-sstv"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
std = ["thiserror/std"]

[dependencies]
libm.workspace = true
rssstv-fskid = { path = "../rssstv-fskid" }
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
rstest.workspace = true
