[workspace]
resolver = "3"
members = [
  "decode-wav",
  "rssstv",
  "rssstv-demodulator",
  "rssstv-dsp",
  "rssstv-fskid",
  "rssstv-sstv",
  "rssstv-template",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0"
authors = ["Yū KOBAYASHI <kb10uy@kb10uy.org>"]

[workspace.dependencies]
anyhow = "1.0"
hound = "3.5"
image = { version = "0.25", default-features = false, features = ["bmp", "jpeg", "png"] }
kdl = "6.7"
libm = "0.2"
proptest = "1.7"
resvg = "0.47"
rstest = "0.26"
thiserror = { version = "2.0", default-features = false }
