//! Embeds the Windows resources the application loads at runtime.
//!
//! `embed-resource` is a host-gated build dependency, so `cfg(target_os)` here
//! reads the same platform Cargo used to select it. Compiling for a non-Windows
//! target from a Windows host is handled by `embed-resource` itself, which
//! reports `NotWindows` and links nothing.

fn main() {
    #[cfg(target_os = "windows")]
    windows::embed_resources();
}

#[cfg(target_os = "windows")]
mod windows {
    use std::{env, fs, path::PathBuf};

    /// Writes the resource script and hands it to the resource compiler.
    ///
    /// The script is generated rather than kept in the tree so the version
    /// stamped into the executable comes from `Cargo.toml` and cannot drift
    /// from the version the application reports.
    pub fn embed_resources() {
        println!("cargo:rerun-if-changed=assets/icon.ico");
        println!("cargo:rerun-if-changed=build.rs");

        let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR should be set"));
        let script = out_dir.join("rssstv.rc");
        fs::write(&script, resource_script()).expect("could not write the resource script");

        // The resource is linked into every artifact rather than the binary
        // alone, so the tests that read the icon back can find it.
        embed_resource::compile_for_everything(&script, embed_resource::NONE)
            .manifest_optional()
            .expect("could not compile the application resources");
    }

    fn resource_script() -> String {
        let icon = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"))
            .join("assets")
            .join("icon.ico");
        let version = Version::from_environment();
        let name = env::var("CARGO_PKG_NAME").expect("package name");
        let description = env::var("CARGO_PKG_DESCRIPTION").unwrap_or_default();

        // The build type is reported so a debug executable is identifiable
        // from its properties alone. VS_FF_DEBUG is 0x1.
        let flags = if env::var("PROFILE").as_deref() == Ok("debug") {
            "0x1L"
        } else {
            "0x0L"
        };

        format!(
            r#"// Generated by build.rs. Edits here are overwritten.
#pragma code_page(65001)

// Identifier 1 is the lowest in the file, which is what Explorer picks.
1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {comma}
PRODUCTVERSION {comma}
FILEFLAGSMASK 0x3fL
FILEFLAGS {flags}
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "{company}"
            VALUE "FileDescription", "{description}"
            VALUE "FileVersion", "{dotted}"
            VALUE "InternalName", "{name}"
            VALUE "LegalCopyright", "{copyright}"
            VALUE "OriginalFilename", "{name}.exe"
            VALUE "ProductName", "RSSSTV"
            VALUE "ProductVersion", "{dotted}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#,
            icon = escape(&icon.display().to_string()),
            comma = version.comma_separated(),
            dotted = version.dotted(),
            company = escape(&company()),
            copyright = escape(&copyright()),
            description = escape(&description),
        )
    }

    /// The four-part version Windows records in the resource.
    struct Version {
        major: String,
        minor: String,
        patch: String,
    }

    impl Version {
        fn from_environment() -> Self {
            let part = |key: &str| env::var(key).unwrap_or_else(|_| "0".to_owned());
            Self {
                major: part("CARGO_PKG_VERSION_MAJOR"),
                minor: part("CARGO_PKG_VERSION_MINOR"),
                patch: part("CARGO_PKG_VERSION_PATCH"),
            }
        }

        /// Windows keeps a fourth field for the build number, which this
        /// project does not track, so it is always zero.
        fn comma_separated(&self) -> String {
            format!("{},{},{},0", self.major, self.minor, self.patch)
        }

        fn dotted(&self) -> String {
            format!("{}.{}.{}", self.major, self.minor, self.patch)
        }
    }

    /// Returns the first author, without the address `Cargo.toml` attaches.
    fn company() -> String {
        let authors = env::var("CARGO_PKG_AUTHORS").unwrap_or_default();
        let first = authors.split(':').next().unwrap_or_default().trim();
        match first.split_once('<') {
            Some((name, _)) => name.trim().to_owned(),
            None => first.to_owned(),
        }
    }

    fn copyright() -> String {
        let license = env::var("CARGO_PKG_LICENSE").unwrap_or_default();
        let holder = company();
        if license.is_empty() {
            format!("Copyright (C) {holder}")
        } else {
            format!("Copyright (C) {holder}. Licensed under {license}.")
        }
    }

    /// Escapes a value for a resource-script string literal.
    fn escape(value: &str) -> String {
        value.replace('\\', r"\\").replace('"', r#"\""#)
    }
}
