[package]
name = "rssstv"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
directories.workspace = true
fluent-bundle.workspace = true
iced.workspace = true
rssstv-audio = { path = "../rssstv-audio" }
rssstv-demodulator = { path = "../rssstv-demodulator" }
rssstv-fskid = { path = "../rssstv-fskid" }
rssstv-sstv = { path = "../rssstv-sstv", features = ["std"] }
unic-langid.workspace = true

[dev-dependencies]
hound.workspace = true
image.workspace = true
rstest.workspace = true
